# Docker made by Cosmo
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '8b8d32cc-41db-462f-984d-1fb1f1b72b05'
  imageRepository: 'lukejdockerluke'
  containerRegistry: 'dockerluke.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
    
stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: MavenAuthenticate@0
      displayName: 'Authenticate to Azure Artifacts feed'
      inputs:
        mavenServiceConnections: 'Cosmo'
    - script: |
        mvn -f src/pom.xml
        mvn deploy
        displayName: 'Publish'
    - task: AzureRmWebAppDeployment@3
      inputs:
        azureSubscription: 'Azure subscription 1(525c7c1f-f5e9-4bf4-8d7a-5b7a06889a12)'
        appType: 'applinux'
        WebAppName: 'dockerluke'
        DockerNamespace: '$(containerRegistry)'
        DockerRepository: '$(imageRepository)'
        DockerImageTag: '$(Build.BuildId)'
        WebAppUri: 'webAppUrl'
        TakeAppOfflineFlag: true
        UseWebDeploy: true
        RenameFilesFlag: true
